steps:
# Fetch the Cloud SQL proxy key from GCS
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'fetch-key'
  args: ['cp', 'gs://wordpress-sigma-436504-wordpress-content/key.json', 'key.json']

# Deploy WordPress PVC
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/wordpress-volumeclaim.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

# Create/Update CloudSQL credentials secret
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    echo "Fetching cluster credentials..."
    gcloud container clusters get-credentials wordpress-cluster --zone us-central1-a --project $PROJECT_ID
    echo "Creating/updating cloudsql-db-credentials secret..."
    kubectl create secret generic cloudsql-db-credentials \
      --from-literal=username=wordpress \
      --from-literal=password=$_DB_PASSWORD \
      --dry-run=client -o yaml | kubectl apply -f - -v=5
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'
  secretEnv: ['_DB_PASSWORD']

# Create CloudSQL instance credentials secret
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    echo "Creating/updating cloudsql-instance-credentials secret..."
    kubectl create secret generic cloudsql-instance-credentials \
      --from-file=key.json=key.json \
      --dry-run=client -o yaml | kubectl apply -f - -v=5
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

# Deploy WordPress deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/wordpress-deployment.yaml', '-v=5']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

# Deploy WordPress service
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/wordpress-service.yaml', '-v=5']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

# Clean up the key file
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'cleanup'
  entrypoint: 'sh'
  args:
  - '-c'
  - 'shred -u key.json'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/wordpress-db-password/versions/latest
    env: '_DB_PASSWORD'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

#serviceAccount: '424615066975-compute@developer.gserviceaccount.com'